- name: Create app directory
  file:
    path: "{{ app_path }}"
    state: directory

- name: Copy docker-compose file
  copy:
    src: "{{ docker_compose_src }}"
    dest: "{{ app_path }}/docker-compose.yml"

- name: Deploy stack
  community.docker.docker_compose:
    project_src: "{{ app_path }}"