- name: Create app directory
  file:
    path: /opt/devtrack
    state: directory

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /opt/devtrack/docker-compose.yml

- name: Launch stack
  command: docker compose up -d
  args:
    chdir: /opt/devtrack